# Generated by Django 3.1.14 on 2022-09-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='ts',
            field=models.IntegerField(default=1663348903),
        ),
    ]
