# Generated by Django 3.1.14 on 2022-10-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220916_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=255)),
                ('ts', models.IntegerField(default=1665602489)),
            ],
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='ts',
            field=models.IntegerField(default=1665602489),
        ),
    ]
