# Generated by Django 3.1.14 on 2022-10-27 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20221017_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.FloatField(default=0.0)),
                ('body_temp', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ts', models.IntegerField(default=1666856492)),
                ('patient_id', models.IntegerField(default=0)),
                ('patient_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ip',
            name='ts',
            field=models.IntegerField(default=1666856492),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='ts',
            field=models.IntegerField(default=1666856492),
        ),
    ]
