# Generated by Django 3.1.14 on 2022-10-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20221027_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='ts',
            field=models.IntegerField(default=1666937841),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ts',
            field=models.IntegerField(default=1666937841),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='ts',
            field=models.IntegerField(default=1666937841),
        ),
    ]
